# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest
image: ubuntu:18.04

before_script:
  - echo "Before script section"
#   - echo "For example you might run an update here or install a build dependency"
#   - echo "Or perhaps you might print out some debugging details"
  - echo "install jdk 11 and maven..."
  - apt-get update -qq && apt-get install -qq openjdk-11-jre-headless -y && apt install -qq maven -y
  - java --version
  - mvn -v

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    # - echo "Do your build here"
    - echo "Compie..."
    - mvn clean compile

test1:
  stage: test
  script:
    # - echo "Do a test here"
    - echo "Unit test..."
    - mvn test
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  script:
    # - echo "Do your deploy here"
    - echo "Deploy..."
    - java -jar target/*.jar
    - curl localhost:8080
