stages:
 - build
 - deploy

before_script:
  - echo "Take a look at root dir..."
  - ls -alF /

after_script:
  - echo "Let's see what we've got..."
  - ls -alF

cache:
  paths:
    - /root/.m2/repository

maven-build:
  stage: build
  image: maven:3.6-jdk-11-slim
  script:
    - echo "Let's verify java and maven first..."
    - java --version
    - mvn -v
    - mvn clean package

heroku-deploy:
  stage: deploy
  image: ruby:2.3
  script:
    - echo "Deploy to Heroku..."
    - apt-get update -qy && apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=hino-pokedex --api-key=$HEROKU_STAGING_API_KEY
