# image: busybox:latest
image: ubuntu:18.04

before_script:
  - echo "Before script section"
#   - echo "For example you might run an update here or install a build dependency"
#   - echo "Or perhaps you might print out some debugging details"
  - echo "install jdk 11 and maven..."
  - apt-get update -qq && apt-get install openjdk-11-jre-headless -qy && apt install maven -qy
  - java --version
  - mvn -v

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    # - echo "Do your build here"
    - echo "We should compile, test and package to save time..."
    - mvn clean package

#test1:
#  stage: test
#  script:
    # - echo "Do a test here"
#    - echo "Unit test..."
#    - mvn test
#    - echo "For example run a test suite"

deploy1:
  stage: deploy
  script:
    # - echo "Do your deploy here"
    - apt-get install curl -qy
    - echo "Deploy..."
    - nohup java -jar target/*.jar > nohup.out &
    - tail nohup.out -n 1
    - curl localhost:8080
