version: "3"
services:
  pokedex:
    # replace username/repo:tag with your name and image details
    image: hinorashi/pokedex:release-1.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8080"
    networks:
      - webnet
networks:
  webnet:
