version: "3"
services:
  pokedex:
    build:
      context: .
    # replace username/repo:tag with your name and image details
    image: hinorashi/pokedex
    container_name: pokedex
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - pokenet
networks:
  pokenet:
