version: "3.8"
services:
  pokedex:
    build:
      context: .
    # replace username/repo:tag with your name and image details
    image: hinorashi/pokedex
    container_name: pokedex
    environment:
      SPRING_PROFILES_ACTIVE: "cloud,h2"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - pokenet

  redis-cache:
    container_name: redis-cache
    image: redis
    volumes:
      - ./redis:/etc/redis
      - ./data/redis-cache/:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/users.acl:/etc/redis/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    ports:
      - "6379:6379" # debug purpose
    networks:
      - pokenet

networks:
  pokenet:
