version: "3.8"
services:
  pokedex:
    build:
      context: .
    # replace username/repo:tag with your name and image details
    image: hinorashi/pokedex
    container_name: pokedex
    # FIXME find a better way
    entrypoint: ["java", "-jar",
                 "-Djavax.net.debug=ssl:handshake",
                 "-Djavax.net.ssl.trustStore=/hino-truststore.p12",
                 "-Djavax.net.ssl.trustStorePassword=hino123",
                 "/app.jar"]
    volumes:
    - ./tls/hino-truststore.p12:/hino-truststore.p12
    environment:
#      SPRING_PROFILES_ACTIVE: "h2"
      SPRING_REDIS_SSL: "true"
      SPRING_REDIS_URL: "redis://pokedex:hino123@redis-cache:6379"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - pokenet

  redis-cache:
    container_name: redis-cache
    image: redis:6.0.5
    volumes:
      - ./redis:/etc/redis
      - ./data/redis-cache/:/data
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379" # debug purpose
    networks:
      - pokenet

networks:
  pokenet:
