server:
  port: 8080

spring:
  application:
    name: pokedex
  jpa:
    open-in-view: false # disable database queries to be performed during view rendering
  datasource: # FIXME change to another DB
    url: jdbc:h2:mem:pokedex;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    mappings:
      enabled: true
